include: package:lints/recommended.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    - always_declare_return_types
    - avoid_unnecessary_containers
    - lines_longer_than_80_chars
    - prefer_const_constructors
    - prefer_final_locals
    - prefer_single_quotes
    - public_member_api_docs
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - unawaited_futures
    - always_put_required_named_parameters_first


