name: nano_core
description: "A pure Dart core package for business logic."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  get_it: ^9.2.0

dev_dependencies:
  test: ^1.24.0
  lints: ^5.0.0
