name: Flutter CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  ci:
    name: Lint, Analyze & Test
    uses: durvalperipato/nano-workflows/.github/workflows/flutter-ci.yml@v1
